from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from rag_pipeline import rag_pipeline

app = FastAPI(
    title="Smart-RAG-Chatbot API",
    description="A Retrieval-Augmented Generation API Service",
    version="1.0.0"
)

# Request Models
class AskRequest(BaseModel):
    question: str

class AskResponse(BaseModel):
    answer: str

@app.get("/", tags=["UI"])
def serve_ui():
    """
    Serves the simple HTML chat interface.
    """
    return FileResponse("index.html")

@app.get("/health", tags=["Health"])
def health_check():
    """
    Health check endpoint to verify the service is running.
    """
    return {"status": "healthy", "service": "Smart-RAG-Chatbot"}


@app.post("/ask", response_model=AskResponse, tags=["RAG"])
def ask_question(request: AskRequest):
    """
    Accepts a question, retrieves context, and returns an answer generated by the LLM.
    """
    if not request.question or not request.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    
    try:
        answer = rag_pipeline.ask(request.question)
        return AskResponse(answer=answer)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")

# This allows running the file directly for testing
if __name__ == "__main__":
    import uvicorn
    import os
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("app:app", host="0.0.0.0", port=port, reload=True)
